#!/usr/bin/env python3
import yaml

# 1) Load original config:
with open("src/config.yaml") as f:
    base = yaml.safe_load(f)
orig = base["species"]

# 2) Paste new species here:
new_species = [
    "Allen's Hummingbird",
    "American Avocet",
    "American Bittern",
    "American Black Duck",
    "American Dipper",
    "American Golden-Plover",
    "American Kestrel",
    "American Oystercatcher",
    "American Pipit",
    "American Redstart",
    "American Three-toed Woodpecker",
    "American White Pelican",
    "American Wigeon",
    "American Woodcock",
    "Ancient Murrelet",
    "Anhinga",
    "Baird's Sparrow",
    "Bald Eagle",
    "Baltimore Oriole",
    "Band-tailed Pigeon",
    "Bank Swallow",
    "Barn Owl",
    "Barrow's Goldeneye",
    "Bay-breasted Warbler",
    "Bell's Vireo",
    "Bendire's Thrasher",
    "Black Oystercatcher",
    "Black Rosy-Finch",
    "Black Skimmer",
    "Black Swift",
    "Black Tern",
    "Black Vulture",
    "Black-and-white Warbler",
    "Black-backed Woodpecker",
    "Black-bellied Plover",
    "Black-billed Cuckoo",
    "Black-billed Magpie",
    "Black-capped Vireo",
    "Black-chinned Hummingbird",
    "Black-chinned Sparrow",
    "Black-crested Titmouse",
    "Black-crowned Night-Heron",
    "Black-headed Grosbeak",
    "Black-legged Kittiwake",
    "Black-throated Blue Warbler",
    "Black-throated Gray Warbler",
    "Black-throated Green Warbler",
    "Blackburnian Warbler",
    "Blackpoll Warbler",
    "Blue-winged Teal",
    "Blue-winged Warbler",
    "Boat-tailed Grackle",
    "Bobolink",
    "Bohemian Waxwing",
    "Boreal Chickadee",
    "Boreal Owl",
    "Brant",
    "Brewer's Blackbird",
    "Brewer's Sparrow",
    "Broad-winged Hawk",
    "Bronzed Cowbird",
    "Brown Creeper",
    "Brown Pelican",
    "Brown-capped Rosy-Finch",
    "Brown-headed Nuthatch",
    "Bufflehead",
    "Bullock's Oriole",
    "Burrowing Owl",
    "California Gull",
    "Calliope Hummingbird",
    "Canada Warbler",
    "Cape May Warbler",
    "Caspian Tern",
    "Cassin's Auklet",
    "Cassin's Finch",
    "Cave Swallow",
    "Cerulean Warbler",
    "Chestnut-collared Longspur",
    "Chestnut-sided Warbler",
    "Cinnamon Teal",
    "Clapper Rail",
    "Clark's Grebe",
    "Clark's Nutcracker",
    "Clay-colored Sparrow",
    "Common Goldeneye",
    "Common Loon",
    "Common Merganser",
    "Common Poorwill",
    "Common Raven",
    "Common Redpoll",
    "Common Tern",
    "Connecticut Warbler",
    "Cordilleran Flycatcher",
    "Crested Caracara",
    "Double-crested Cormorant",
    "Dovekie",
    "Dunlin",
    "Dusky Flycatcher",
    "Dusky/Sooty Grouse",
    "Eared Grebe",
    "Eastern Whip-poor-will",
    "Emperor Goose",
    "Eurasian Wigeon",
    "Evening Grosbeak",
    "Ferruginous Hawk",
    "Fish Crow",
    "Florida Scrub-Jay",
    "Forster's Tern",
    "Franklin's Gull",
    "Gadwall",
    "Gila Woodpecker",
    "Gilded Flicker",
    "Glaucous-winged Gull",
    "Glossy Ibis",
    "Golden Eagle",
    "Golden-cheeked Warbler",
    "Golden-crowned Kinglet",
    "Golden-fronted Woodpecker",
    "Golden-winged Warbler",
    "Gray Flycatcher",
    "Gray Vireo",
    "Gray-cheeked Thrush",
    "Gray-crowned Rosy-Finch",
    "Great Black-backed Gull",
    "Great Gray Owl",
    "Greater Sage-Grouse",
    "Greater Scaup",
    "Greater White-fronted Goose",
    "Greater Yellowlegs",
    "Green-tailed Towhee",
    "Gull-billed Tern",
    "Gyrfalcon",
    "Hairy Woodpecker",
    "Hammond's Flycatcher",
    "Henslow's Sparrow",
    "Hepatic Tanager",
    "Hermit Thrush",
    "Hermit Warbler",
    "Herring Gull",
    "Hooded Merganser",
    "Hooded Oriole",
    "Hooded Warbler",
    "Horned Grebe",
    "House Finch",
    "Hutton's Vireo",
    "Juniper Titmouse",
    "King Eider",
    "King Rail",
    "Kittlitz's Murrelet",
    "Laughing Gull",
    "Lawrence's Goldfinch",
    "Le Conte's Sparrow",
    "Le Conte's Thrasher",
    "Least Bittern",
    "Least Flycatcher",
    "Least Grebe",
    "Least Tern",
    "Lesser Prairie-Chicken",
    "Lesser Scaup",
    "Lesser Yellowlegs",
    "Lewis's Woodpecker",
    "Little Gull",
    "Long-billed Curlew",
    "Long-billed Thrasher",
    "Long-eared Owl",
    "Louisiana Waterthrush",
    "Magnolia Warbler",
    "Mallard",
    "Mangrove Cuckoo",
    "Marbled Godwit",
    "Marsh Wren",
    "McCown's Longspur",
    "Merlin",
    "Mexican Jay",
    "Mississippi Kite",
    "Montezuma Quail",
    "Mountain Bluebird",
    "Mountain Chickadee",
    "Mountain Plover",
    "Mountain Quail",
    "Mourning Warbler",
    "Nashville Warbler",
    "Nelson's/Saltmarsh Sparrow (Sharp-tailed Sparrow)",
    "Northern Fulmar",
    "Northern Gannet",
    "Northern Harrier",
    "Northern Hawk Owl",
    "Northern Pygmy-Owl",
    "Northern Saw-whet Owl",
    "Northern Shoveler",
    "Olive Warbler",
    "Orchard Oriole",
    "Osprey",
    "Ovenbird",
    "Pacific Golden-Plover",
    "Pacific-slope Flycatcher",
    "Painted Redstart",
    "Palm Warbler",
    "Parasitic Jaeger",
    "Peregrine Falcon",
    "Philadelphia Vireo",
    "Pigeon Guillemot",
    "Pine Grosbeak",
    "Pine Siskin",
    "Pine Warbler",
    "Pinyon Jay",
    "Piping Plover",
    "Pomarine Jaeger",
    "Prairie Falcon",
    "Purple Finch",
    "Purple Sandpiper",
    "Pygmy Nuthatch",
    "Razorbill",
    "Red Crossbill",
    "Red Knot",
    "Red-breasted Merganser",
    "Red-breasted Nuthatch",
    "Red-breasted Sapsucker",
    "Red-cockaded Woodpecker",
    "Red-faced Warbler",
    "Red-naped Sapsucker",
    "Red-necked Grebe",
    "Red-throated Loon",
    "Reddish Egret",
    "Redhead",
    "Rhinoceros Auklet",
    "Ring-billed Gull",
    "Ring-necked Duck",
    "Rock Sandpiper",
    "Roseate Spoonbill",
    "Royal Tern",
    "Ruddy Turnstone",
    "Ruffed Grouse",
    "Rufous Hummingbird",
    "Rufous-crowned Sparrow",
    "Rusty Blackbird",
    "Sage Sparrow",
    "Sage Thrasher",
    "Sandhill Crane",
    "Sandwich Tern",
    "Scarlet Tanager",
    "Seaside Sparrow",
    "Sedge Wren",
    "Semipalmated Plover",
    "Sharp-tailed Grouse",
    "Short-billed Dowitcher",
    "Short-eared Owl",
    "Smith's Longspur",
    "Snowy Owl",
    "Snowy Plover",
    "Solitary Sandpiper",
    "Spotted Owl",
    "Spotted Sandpiper",
    "Sprague's Pipit",
    "Stilt Sandpiper",
    "Surfbird",
    "Swainson's Hawk",
    "Swallow-tailed Kite",
    "Swamp Sparrow",
    "Tennessee Warbler",
    "Thayer's Gull",
    "Thick-billed Murre",
    "Townsend's Solitaire",
    "Townsend's Warbler",
    "Tree Swallow",
    "Tricolored Blackbird",
    "Tricolored Heron",
    "Trumpeter Swan",
    "Tundra Swan",
    "Varied Thrush",
    "Vaux's Swift",
    "Veery",
    "Vesper Sparrow",
    "Violet-green Swallow",
    "Virginia's Warbler",
    "Western Bluebird",
    "Western Grebe",
    "Western Gull",
    "Western Screech-Owl",
    "Western Tanager",
    "Western Wood-Pewee",
    "Whimbrel",
    "White-breasted Nuthatch",
    "White-crowned Pigeon",
    "White-faced Ibis",
    "White-headed Woodpecker",
    "White-tailed Hawk",
    "White-tailed Kite",
    "White-throated Sparrow",
    "White-throated Swift",
    "White-winged Crossbill",
    "Wild Turkey",
    "Willet",
    "Williamson's Sapsucker",
    "Willow Flycatcher",
    "Wilson's Phalarope",
    "Wilson's Plover",
    "Wilson's Warbler",
    "Winter/Pacific Wren",
    "Wood Duck",
    "Wood Stork",
    "Wood Thrush",
    "Worm-eating Warbler",
    "Yellow Rail",
    "Yellow-bellied Flycatcher",
    "Yellow-bellied Sapsucker",
    "Yellow-billed Loon",
    "Yellow-billed Magpie",
    "Yellow-headed Blackbird",
    "Yellow-throated Vireo",
    "Yellow-throated Warbler",
    "Zone-tailed Hawk",
]

# 3) Merge, dedupe, and sort:
combined = sorted(dict.fromkeys(orig + new_species))

# 4) Write out a new config
out = {
    "species": combined,
    "audio": base["audio"]
}
with open("src/config_extended.yaml", "w") as f:
    yaml.safe_dump(out, f, sort_keys=False)

print(f"Wrote {len(combined)} unique species to src/config_extended.yaml")
