# src/config_remarkable100.yaml

species:
  - Northern Cardinal
  - American Robin
  - Black-capped Chickadee
  - Mourning Dove
  - Blue Jay
  - House Sparrow
  - American Goldfinch
  - Carolina Wren
  - Downy Woodpecker
  - Mourning Warbler
  - Red-winged Blackbird
  - Song Sparrow
  - White-breasted Nuthatch
  - House Finch
  - European Starling
  - Dark-eyed Junco
  - Tufted Titmouse
  - Yellow Warbler
  - Eastern Bluebird
  - Common Grackle

  # — Remarkable Birds: The Top 100 —
  - Ostrich
  - Brown Kiwi
  - Emperor Penguin
  - Common Loon
  - Wandering Albatross
  - Snow Petrel
  - Red-billed Tropicbird
  - Dalmatian Pelican
  - Northern Gannet
  - Flightless Cormorant
  - Magnificent Frigatebird
  - Eurasian Bittern
  - European White Stork
  - Shoebill
  - Scarlet Ibis
  - Black-faced Spoonbill
  - Lesser Flamingo
  - Bewick’s Swan
  - Snow Goose
  - Red-breasted Goose
  - Common Eider
  - California Condor
  - Bald Eagle
  - Lammergeyer
  - Montagu’s Harrier
  - Harpy Eagle
  - Secretary Bird
  - Peregrine
  - Malleefowl
  - Western Capercaillie
  - Satyr Tragopan
  - Congo Peafowl
  - Hoatzin
  - Whooping Crane
  - Red-crowned Crane
  - Corncrake
  - Takahe
  - Kagu
  - Sunbittern
  - Great Bustard
  - Ibisbill
  - Black-winged Stilt
  - Egyptian Plover
  - Northern Lapwing
  - Red Knot
  - Ruff
  - Spoon-billed Sandpiper
  - Red-necked Phalarope
  - Plains-wanderer
  - Ross’s Gull
  - Arctic Tern
  - Atlantic Puffin
  - Mauritius Pink Pigeon
  - Kakapo
  - Hyacinth Macaw
  - Great Blue Turaco
  - Common Cuckoo
  - Greater Roadrunner
  - Snowy Owl
  - Eurasian Eagle-Owl
  - Oilbird
  - Common Swift
  - Sword-billed Hummingbird
  - Resplendent Quetzal
  - Laughing Kookaburra
  - Common Kingfisher
  - Blue-crowned Motmot
  - European Bee-eater
  - Lilac-breasted Roller
  - Hoopoe
  - Rhinoceros Hornbill
  - Toco Toucan
  - Eurasian Wryneck
  - Ivory-billed Woodpecker
  - Gurney’s Pitta
  - Bearded Bellbird
  - Andean Cock-of-the-Rock
  - Red-capped Manakin
  - Noisy Scrub-bird
  - Superb Lyrebird
  - Eurasian Skylark
  - Barn Swallow
  - Bohemian Waxwing
  - Hypocolius
  - Winter Wren
  - Northern Mockingbird
  - Common Nightingale
  - Dartford Warbler
  - Gray-necked Picathartes
  - Wallcreeper
  - Long-tailed Tit
  - Red-backed Shrike
  - Wilson’s Bird-of-paradise
  - Northern Raven
  - New Caledonian Crow
  - Kirtland’s Warbler
  - Darwin’s Finches
  - Long-tailed Paradise-whydah

audio:
  sample_rate: 16000
  chunk_duration: 5   # seconds per clip
